baseURL: https://blog.rainaldi.dev
languageCode: en-us
defaultContentLanguage: en
title: Lou Rainaldi
theme: cupper-hugo-theme
googleAnalytics: UA-136871287-1
disqusShortname: rainaldi-dev

taxonomies:
  tag: tags

permalinks:
  post: posts/:year/:month/:title/

imaging:
  quality: 99

params:
  description: My personal blog on technologies and rants about life.
  homeMetaContent: My personal blog on technologies and rants about life.
  footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Firebase](https://firebase.google.com/docs/hosting).
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: Jan 2, 2006
  codePenUser: someUser

menu:
  nav:
    - name: Home
      url: /
      weight: 1
    - name: Blog
      url: /post/
      weight: 2
    - name: Tags
      url: /tags/
      weight: 3
    - name: About
      url: /about/
      weight: 4
    - name: RSS
      url: /index.xml
      weight: 5
